### ISSUE TITLE
An error :"requestThunk is not a function" thrown when I try to pipe request

### ISSUE THREAD

**Issue by wspl** [denys/co-request#22]
My code is similar to the sample in README.md:
```javascript
function pipeRequest(readable, requestThunk){
  return function(cb){
    readable.pipe(requestThunk(cb));
  }
}

//..and then:

  var value = yield pipeRequest(this.req, request({...}));
```
But an error thrown:

```
  TypeError: requestThunk is not a function
      at Object.<anonymous> (/home/project/Ivory/src/reverse.js:7:19)
      at /home/project/Ivory/node_modules/koa/node_modules/co/index.js:136:8
      at new Promise (/home/project/Ivory/node_modules/babel/node_modules/babel-                           core/node_modules/core-js/modules/es6.promise.js:184:7)
      at Object.thunkToPromise (/home/project/Ivory/node_modules/koa/node_module                           s/co/index.js:135:10)
      at Object.toPromise (/home/project/Ivory/node_modules/koa/node_modules/co/                           index.js:119:55)
      at next (/home/project/Ivory/node_modules/koa/node_modules/co/index.js:99:                           29)
      at onFulfilled (/home/project/Ivory/node_modules/koa/node_modules/co/index                           .js:69:7)
      at /home/project/Ivory/node_modules/koa/node_modules/co/index.js:54:5
      at new Promise (/home/project/Ivory/node_modules/babel/node_modules/babel-                           core/node_modules/core-js/modules/es6.promise.js:184:7)
      at Object.co (/home/project/Ivory/node_modules/koa/node_modules/co/index.j                           s:50:10)
```
Umm, this situation only occurred in the lastest promisified version.

Is there a better way to solve this problem without install co-request with an older version(such as 0.2.0 is working well)?

**Comment by denys** [comment]
No, sorry. Co was updated to use Promises instead of thunks. Version change of co-request is only about that changes in Co. So in your case it will be better to switch co-request to previous version.

**Comment by RHavar** [comment]
So shouldn't the readme be updated with how to do it in the new version?

**Comment by denys** [comment]
@RHavar sure, i will check soon. Have changed my main mail, so your comment was lost.
